#ARG os=ubuntu2204 tag=8.5.0-cuda-11.7
#FROM nvidia/cuda:11.7.0-cudnn8-devel-ubuntu22.04
#RUN dpkg -i nv-tensorrt-local-repo-${os}-${tag}_1.0-1_amd64.deb \
#	&& cp /var/nv-tensorrt-local-repo-${os}-${tag}/*-keyring.gpg /usr/share/keyrings/ \
#	&& apt-get update

FROM nvcr.io/nvidia/tensorrt:22.10-py3

# install libtorch
RUN cd ~/ && wget https://download.pytorch.org/libtorch/cu118/libtorch-cxx11-abi-shared-with-deps-2.0.0%2Bcu118.zip \
	&& unzip libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip -d /usr/local/ \
	&& rm -f libtorch-cxx11-abi-shared-with-deps-2.0.0+cu118.zip

# install opencv 
RUN apt update && apt install libopencv-dev -y 

# install python essential dependencies
RUN pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118 
RUN pip3 install numpy pillow matplotlib pycocotools opencv-python onnx onnxruntime -i https://pypi.tuna.tsinghua.edu.cn/simple